title: april tuesday shen

markdown: kramdown
theme: jekyll-theme-cayman

permalink: /blog/:year/:month/:day/:title

plugins:
  - jemoji

collections:
  projects:
    output: true
    permalink: /:collection/:name