title: april tuesday shen

markdown: kramdown
mathjax: true
theme: jekyll-theme-cayman

permalink: /blog/:year/:month/:day/:title

tag_page: /blog/tags

plugins:
  - jemoji
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /:collection/:name
